### ISSUE TITLE
[BUG] deno import

### ISSUE THREAD

**Issue by illyrius666** [wrapperup/vento-plugin-fragments#1]
https://deno.land/x/vento_plugin_fragments@0.1.0/mod.ts
only works like this:
https://deno.land/x/vento_plugin_fragments@0.1.0/src/mod.ts

**Comment by wrapperup** [comment]
Thanks for reporting, I'll update the readme.

**Comment by wrapperup** [comment]
Resolved in 0.1.1, you can import it via `https://deno.land/x/vento_plugin_fragments@0.1.1/mod.ts` as shown in the README.
